### ISSUE TITLE
Sending multiple keys simultaneously throws nasty error (Should throw nice error)

### ISSUE THREAD

**Issue by luke-hill** [appium/ruby_lib_core#317]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Feature Request

## Environment
- iOS12 iPhone 8
- iOS12 iPhone 11
- iOS13 iPhone 11

## Actual behaviour and steps to reproduce
`element.send_keys([:shift, :end])`

## Expected behaviour
```
ArgumentError, "You cannot send multiple keystrokes simultaneously to a mobile driven device"
```

## Actual behaviour
```
An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of '(
    pointer,  key
)' types are supported. 'key' is given instead for action with id 'keyboard'" UserInfo={NSLocalizedDescription=Only actions of '(
    pointer,  key
)' types are supported. 'key' is given instead for action with id 'keyboard'} (Selenium::WebDriver::Error::UnknownError)

UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of '(
    pointer,  key
)' types are supported. 'key' is given instead for action with id 'keyboard'" UserInfo={NSLocalizedDescription=Only actions of '(
    pointer, key
)' types are supported. 'key' is given instead for action with id 'keyboard'}
    at errorFromW3CJsonCode (/usr/local/.browserstack/appium_1.17.0_bstack/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
    at ProxyRequestError.getActualError (/usr/local/.browserstack/appium_1.17.0_bstack/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
    at JWProxy.command (/usr/local/.browserstack/appium_1.17.0_bstack/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:265:8)
```
## Any additional comments

Maybe some more documentation would be good on this note.

**Comment by KazuCocoa** [comment]
As a note. The message itself was from Appium server, so changing the message should be in appium server side. (Not client side)

Btw, below code worked with our test app. How about using the latest Appium version? (1.20.2 is the latest for now)
I haven't tested on real devices, so potentially the error happens only on real devices by XCTest internal (by Apple)

```
[6] pry(#<AppiumLibCoreTest::DriverTest>)> @@driver.find_element :predicate, 'value == "Placeholder text"'
=> #<Selenium::WebDriver::Element:0x2b57069392a75fd6 id="AA000000-0000-0000-0737-000000000000">
[7] pry(#<AppiumLibCoreTest::DriverTest>)> e = @@driver.find_element :predicate, 'value == "Placeholder text"'
=> #<Selenium::WebDriver::Element:0x2b57069392a75fd6 id="AA000000-0000-0000-0737-000000000000">
[8] pry(#<AppiumLibCoreTest::DriverTest>)> e.send_keys [:shift, :end]
```

```
[HTTP] --> POST /wd/hub/session/2a7c701c-23a5-4ecc-aac5-6aa0d4070f95/element/AA000000-0000-0000-0737-000000000000/value
[HTTP] {"value":["","",""],"text":""}
[debug] [W3C (2a7c701c)] Calling AppiumDriver.setValue() with args: [["","",""],"AA000000-0000-0000-0737-000000000000","2a7c701c-23a5-4ecc-aac5-6aa0d4070f95"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [WD Proxy] Matched '/element/AA000000-0000-0000-0737-000000000000/value' to command name 'setValue'
[debug] [Protocol Converter] Added 'text' property "" to 'setValue' request body
[debug] [WD Proxy] Proxying [POST /element/AA000000-0000-0000-0737-000000000000/value] to [POST http://127.0.0.1:8100/session/C3440797-CADD-4F2F-8611-5D866063A989/element/AA000000-0000-0000-0737-000000000000/value] with body: {"value":["","",""],"text":""}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"C3440797-CADD-4F2F-8611-5D866063A989"}
[debug] [W3C (2a7c701c)] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/2a7c701c-23a5-4ecc-aac5-6aa0d4070f95/element/AA000000-0000-0000-0737-000000000000/value 200 246 ms - 14
```

<img src="https://user-images.githubusercontent.com/5511591/109862241-8eaabe00-7ca3-11eb-9084-d07aa39b10d2.png" width=300>

**Comment by luke-hill** [comment]
Oki so I was using a mix of appium 1.16 and appium 1.17. Reasons are that appium 1.16 is the latest you can use on iOS11 I believe (So I'll just mark this as unfixable for iOS11)
iOS12/13 I haven't re-tested on a later appium. I'll try this later today. But you're suggesting upgrading appium "should" help?

**Comment by luke-hill** [comment]
I upgraded appium version to 1.20.2 on ios13, ran the same test. Same error occurred. (Didn't test on lower versions).

**Comment by KazuCocoa** [comment]
Then, I guess the root cause is in XCTest internal against real devices. Only Apple can modify the message/behavior.

Potentially Appium could catch errors by XCTest framework and modify the error message, but it seems the behavior depends on the device under test. So, it is not easy to unify the message in Appium layer with checking the response by XCTest since the XCTest is a black box. No one can guarantee the message by XCTest will not change. We won't modify errors by XCTest too much.

Btw, I'll try the same command https://github.com/appium/ruby_lib_core/issues/317#issuecomment-790004327 on a real device with iOS 12 tomorrow. If it will work, perhaps the error may depend on the target element.

**Comment by luke-hill** [comment]
Is XCUITest closed source? Or is there a way we can ask them to fix that?

**Comment by KazuCocoa** [comment]
> Is XCUITest closed source?

Yes. https://developer.apple.com/documentation/xctest

> is there a way we can ask them to fix that?
It could be in https://developer.apple.com/bug-reporting/ , but it depends on their priority.

**Comment by KazuCocoa** [comment]
I tried on a real device. `e.send_keys [:shift, :end]` worked as same.

Btw, I wondered the error message was by w3c actions. `@driver.action.send_keys([:shift, :end]).perform` sends W3C action keys as https://gist.github.com/KazuCocoa/b03d89711ae60ab82a91cbb657f0b1ea .


Could you share the full appium log and your appium_lib_core version?
The error log message is probably appium/WebDriverAgent layer to convert W3C actions to appium/WebDriverAgent  actions if it was W3C actions. But `element.send_keys` should not send W3C actions...

**Comment by luke-hill** [comment]
So the way I'm running this is I have a Capybara ruby driver. So if you can tell me how to configure everything you need I'll do that.

I'm running executions for the legit phones through browserstack. I'm guessing this would be a specific setting somewhere in the driver capabilities (But as you well know, these aren't very well documented)

**Comment by luke-hill** [comment]
Also from your gist. Does that mean sending 2 keys simultaneously on a phone "should" work? If so this is definitely a bug then. Because that fails for me.

I've got a PR in place where we bump the appium versions a little bit (We were using a combination of 1.16 and 1.17)

**Comment by KazuCocoa** [comment]
I don't think this is capabilities stuff.

I guess https://github.com/appium/appium_capybara has some issues sending W3C actions.
Could you share the full Appium log and Gem dependencies to understand your situation?
