### ISSUE TITLE
The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib_core#386]
Maybe routes by plugins have an issue in current latest beta:
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=21859&view=logs&j=dbeb3e1e-1d01-5eac-7795-96e0486c2707&t=a8cc23d2-49f0-52bc-7795-8304999a5a74

```
Progress: |=======ERROR AppiumLibCoreTest::DriverTest#test_batch_combination_ruby_script (255.21s)
Minitest::UnexpectedError:         Selenium::WebDriver::Error::UnknownCommandError: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:109:in `request'
            /Users/runner/work/1/s/lib/appium_lib_core/common/base/http_default.rb:97:in `call'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
            /Users/runner/work/1/s/lib/appium_lib_core/common/device/execute_driver.rb:34:in `execute_driver'
            /Users/runner/work/1/s/lib/appium_lib_core/common/base/driver.rb:1100:in `execute_driver'
            /Users/runner/work/1/s/test/functional/ios/driver_test.rb:169:in `test_batch_combination_ruby_script'

================ERROR AppiumLibCoreTest::DriverTest#test_batch_only_return (309.80s)
Minitest::UnexpectedError:         Selenium::WebDriver::Error::UnknownCommandError: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:109:in `request'
            /Users/runner/work/1/s/lib/appium_lib_core/common/base/http_default.rb:97:in `call'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
            /Users/runner/work/1/s/lib/appium_lib_core/common/device/execute_driver.rb:34:in `execute_driver'
            /Users/runner/work/1/s/lib/appium_lib_core/common/base/driver.rb:1100:in `execute_driver'
            /Users/runner/work/1/s/test/functional/ios/driver_test.rb:153:in `test_batch_only_return'

================ERROR AppiumLibCoreTest::DriverTest#test_batch (349.82s)
Minitest::UnexpectedError:         Selenium::WebDriver::Error::UnknownCommandError: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:109:in `request'
            /Users/runner/work/1/s/lib/appium_lib_core/common/base/http_default.rb:97:in `call'
            /Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
            /Users/runner/work/1/s/lib/appium_lib_core/common/device/execute_driver.rb:34:in `execute_driver'
            /Users/runner/work/1/s/lib/appium_lib_core/common/base/driver.rb:1100:in `execute_driver'
            /Users/runner/work/1/s/test/functional/ios/driver_test.rb:141:in `test_batch'

```

**Comment by KazuCocoa** [comment]
Batch, image reoutes
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=21859&view=logs&j=6d996671-0891-51e9-9212-65f6efb2b72b

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/17025 is probably this issue. Close this for now.
